---
version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  api:
    build: ./dcms
    volumes:
      - ./dcms/dcms:/opt/dcms/dcms:ro
      - ./certs:/certs:ro
    ports:
      - "443:443"
    environment:
      DEBUG: "true"
      DATABASE_URL: postgresql://user:pass@db/db
    depends_on:
      - db

  bot:
    build: ./cms_bot
    env_file: ./cms_bot/.env
    environment:
      DATABASE_URL: postgresql://user:pass@db/db
    depends_on:
      - db
